version: "3.7"
 
# USAGE: 
# Create and start the cluster: docker-compose up -d 
# Tear down the cluster: docker-compose down 
# Reove everything including the volumes: docker-compose down -v  
services: 

# 1. Syslog server 
  app: 
    build: ./app 
    hostname: syslog 
      #container_name: syslog 
    restart: always
    network_mode: "host"
    volumes:
      - "./config/rsyslog.conf:/etc/rsyslog.conf"
      - "./config/rsyslog.d:/etc/rsyslog.d" 
      - "./data:/data" 
        #ports: 
        #- 514:514
        #- 514:514/udp
    cap_add:
      - SYSLOG

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
      #container_name: zookeeper
      #ports:
      #- "2181:2181"
    network_mode: host
    volumes:
      - ./data/zookeeper:/data/zookeeper
    environment:
      ZOO_PORT: 2181
      ZOO_DATA_DIR: /data/zookeeper/data
      ZOO_DATA_LOG_DIR: /data/zookeeper/logs
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=10.10.27.123:2888:3888

  kafka:
    image: wurstmeister/kafka
    restart: always
      #container_name: kafka
    network_mode: host
    volumes:
      - ./data/kafka:/data/kafka
      #ports:
      #- "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_PORT: 9092
      KAFKA_HEAP_OPTS: -Xms1g -Xmx1g
      KAFKA_HOST_NAME: 10.32.0.3
      KAFKA_ADVERTISED_HOST_NAME: 10.32.0.3
      KAFKA_LOG_DIRS: /data/kafka
      KAFKA_ZOOKEEPER_CONNECT: 10.32.0.3:2181
      KAFKA_LOG_RETENTION_HOURS: 72
